#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elmah
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\ErrorMailHtmlPage.cshtml"
    using Elmah;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ErrorMailHtmlPage : RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 4 "..\..\ErrorMailHtmlPage.cshtml"
  
    // NB cast is not really required, but aids with intellisense!
    var error = (Error) this.Error;


            
            #line default
            #line hidden
WriteLiteral("<html>\r\n    <head>\r\n        <title>Error: ");


            
            #line 10 "..\..\ErrorMailHtmlPage.cshtml"
                 Write(error.Message);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    </head>\r\n    <body style=\"font-family: verdana, arial, helvetic; fo" +
"nt-size: small;\">\r\n        <p style=\"font-size: medium; font-style: italic; colo" +
"r: maroon;\">");


            
            #line 13 "..\..\ErrorMailHtmlPage.cshtml"
                                                                    Write(error.Type);

            
            #line default
            #line hidden
WriteLiteral(": ");


            
            #line 13 "..\..\ErrorMailHtmlPage.cshtml"
                                                                                 Write(error.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 14 "..\..\ErrorMailHtmlPage.cshtml"
         if (error.Time != DateTime.MinValue)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>Generated: ");


            
            #line 16 "..\..\ErrorMailHtmlPage.cshtml"
                     Write(error.Time.ToUniversalTime().ToString("r"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 17 "..\..\ErrorMailHtmlPage.cshtml"
        }

            
            #line default
            #line hidden

            
            #line 18 "..\..\ErrorMailHtmlPage.cshtml"
         if (error.Detail.Length != 0)
        {

            
            #line default
            #line hidden


WriteLiteral("<pre style=\"padding: 1em; background-color: #FFFFCC; font-size: small;\">");


            
            #line 23 "..\..\ErrorMailHtmlPage.cshtml"
                                                                                 Write(error.Detail);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 24 "..\..\ErrorMailHtmlPage.cshtml"
        }

            
            #line default
            #line hidden

            
            #line 25 "..\..\ErrorMailHtmlPage.cshtml"
         foreach (var collection in 
            from collection in new[] 
            {
                new
                {
                    Id    = "ServerVariables",
                    Title = "Server Variables",
                    Items = error.ServerVariables,
                }
            }
            let data = collection.Items
            where data != null && data.Count > 0
            let items = from i in Enumerable.Range(0, data.Count)
                        select KeyValuePair.Create(data.GetKey(i), data[i])
            select new
            {
                collection.Id, 
                collection.Title,
                Items = items.OrderBy(e => e.Key, StringComparer.OrdinalIgnoreCase)
            }
        )
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n                <h1 style=\"font-size: small;\">");


            
            #line 48 "..\..\ErrorMailHtmlPage.cshtml"
                                         Write(collection.Title);

            
            #line default
            #line hidden
WriteLiteral(@"</h1>
                <table style=""border-collapse: collapse; border-spacing: 0; border: 1px solid black; width: 100%;"">
                    <tr style=""vertical-align: top;"">
                        <th style=""text-align: left; border: 1px solid black; padding: 4px; font-weight: bold; font-size: small;"">Name</th>            
                        <th style=""text-align: left; border: 1px solid black; padding: 4px; font-weight: bold; font-size: small;"">Value</th></tr>
");


            
            #line 53 "..\..\ErrorMailHtmlPage.cshtml"
                 foreach (var item in collection.Items)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr style=\"vertical-align: top;\">\r\n                        <t" +
"d style=\"border: 1px solid black; padding: 4px; font-size: small;\">");


            
            #line 56 "..\..\ErrorMailHtmlPage.cshtml"
                                                                                        Write(item.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td style=\"border: 1px solid black; padding: 4px; " +
"font-size: small;\">");


            
            #line 57 "..\..\ErrorMailHtmlPage.cshtml"
                                                                                        Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</td></tr>\r\n");


            
            #line 58 "..\..\ErrorMailHtmlPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                </table>\r\n            </div>\r\n");


            
            #line 61 "..\..\ErrorMailHtmlPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <p>");


            
            #line 62 "..\..\ErrorMailHtmlPage.cshtml"
       Write(RenderPartial<PoweredBy>());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
